#!/usr/bin/env bash
# script to copy file to server

if [ $# -lt 3 ]; then
   echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
   exit 1
   fi

# disable strict host key ckecking
SCP_OPTIONS="-o StrictHostKeyChecking=no"
scp -i "$4" "$1" "$3@$2:~/"
