#!/usr/bin/env bash
# setup install and setup nginx web server with default page

#  install nginx in non interactive mode
sudo apt-get -y update
sudo apt-get -y install nginx

# create sample page in location
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# start ngnx service 
sudo service nginx start
