#!/usr/bin/env bash
# This script intstalls nginx with default configurations

sudo apt update -y
sudo apt install haproxy -y

# add frontend to file
sudo printf "frontend http\n" > /etc/haproxy/haproxy.cfg
sudo printf "\t\tbind *:80\n" >> /etc/haproxy/haproxy.cfg
sudo printf "\t\tmode http\n" >> /etc/haproxy/haproxy.cfg
sudo printf "\t\tdefault_backend web-backend\n" >> /etc/haproxy/haproxy.cfg

#configure nackend
sudo printf "backend  web_backend\n" > /etc/haproxy/haproxy.cfg
sudo printf "\t\tmode http" >> /etc/haproxy/haproxy.cfg
sudo printf "\t\tserver 229284-web-01 52.205.91.64:80\n" >> /etc/haproxy/haproxy.cfg
sudo printf "\t\tserver 229284-web-01 54.160.105.186:80\n" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
