#!/usr/bin/env bash
# This script installs HAProxy with basic configurations using the 'service' command

# Install HAProxy
sudo apt update -y
sudo apt install haproxy -y

# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
# HAProxy Configuration

# Frontend configuration
frontend http
    bind *:80
    mode http
    default_backend web-backend

# Backend configuration
backend web-backend
    mode http
    server 229284-web-01 52.205.91.64:80
    server 229284-web-02 54.160.105.186:80
EOL

# Enable and start HAProxy service
service haproxy restart
