#!/usr/bin/python3
"""
Write a recursive function that queries the Reddit API and
returns a list containing the titles of all hot articles for
a given subreddit. If no results are found for the given
subreddit, the function should return None.
"""
import requests


def recurse(subreddit, hot_list=[], counter=0):
    """
    print top 10 hot subreddits
    """
    url = f"https://www.reddit.com/r/{subreddit}/.json"
    ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Ge"
    ua += "cko/20100101 Firefox/100.0"
    headers = {"User-Agent": ua}
    try:
        if counter == 0:
            sub_num = requests.get(url, headers=headers).json()
            sub_num = sub_num.get("data").get("children")
            hot_list.append(sub_num)
        
        sub_num = hot_list[0]
        if counter < len(sub_num):
            hot_list.append(sub_num[counter].get("data").get("title"))
            counter += 1
            return recurse(subreddit, hot_list, counter)
        else:
            return hot_list[2:]
    except Exception as e:
        return None
