#!/usr/bin/env bash
# backup database as compressed file
mysqldump --all-databases -u root --password="$1" > backup.sql
current_date=$(date +'%d-%m-%Y')
file_name="$current_date.tar.gz"
tar -czvf "$file_name" backup.sql
