#!/usr/bin/env bash
# display list of currently running processes
# Run ps with appropriate options to show all processes and their hierarchy
ps_out=$(ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest)

# Display the process list
echo "$ps_out"
