#!/usr/bin/env bash
# Function to handle SIGTERM signal
function handle_sigterm() {
  echo "I hate the kill command"
}

# Function to handle SIGINT signal
function handle_sigint() {
  echo "Y U no love me?!"
}

# Function to clean up and exit (SIGTERM or SIGQUIT)
function cleanup_and_exit() {
  rm -f /var/run/myscript.pid
  exit 0
}

# Set up the traps to catch signals and call the appropriate functions
trap 'cleanup_and_exit' SIGTERM SIGQUIT
trap 'handle_sigint' SIGINT
trap 'handle_sigterm' SIGTERM

# Store PID appropriate file
echo $$ > /var/run/myscript.pid

# Infinite loop
while true; do
  echo "To infinity and beyond"
  sleep 2
done
