#!/usr/bin/env bash
# display numbers based on conditions using bash case statement structure
counter=1
while((counter <= 20))
do
   case $counter in
	   4)
		   echo "$counter"
		   echo "bad luck from China"
		   ;;
	   9)
		   echo "$counter"
                   echo "bad luck from Japan"
		   ;;
	   17)
		   echo "$counter"
                   echo "bad luck from Italy"
                   ;;
	   *)
		   echo "$counter"
		   ;;
   esac
   ((counter++))
done
