#!/usr/bin/env bash
# configure ubuntu server hosts file

# localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8.
# The checker is running on Docker, so make sure to read this(implemented)

cp /etc/hosts ~/hosts.new
echo "127.0.0.2     localhost" > ~/hosts.new
echo "8.8.8.8     facebook.com" >> ~/hosts.new
cat ~/hosts.new >  /etc/hosts
